import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider, type ThemeConfig } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme:ThemeConfig = {
  components:{
    Input:{
      lineWidth:10,
      fontSize:100
    },
    InputNumber:{
      lineWidth:10,
      fontSize:100
    },
    Form:{
      labelFontSize:10,
      lineWidth:10,
      lineWidthBold:10
    },
    List:{
      contentWidth:10,
      fontSize:100,

    }
    
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider theme={theme}>{children}</ConfigProvider>
      </body>
    </html>
  );
}
